services:
  # ==== Database ====
  db:
    image: postgres:16-alpine
    container_name: pg
    restart: unless-stopped
    ports:
      - "${DB_LOCAL_PORT}:${DB_INSIDE_CONTAINER_PORT}"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SELECTED_DB: ${SELECTED_DB}
      PGDATA: ${PGDATA}
    volumes:
      - pgdata:${PGDATA}
      - ./database/set-up:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${SELECTED_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    depends_on: [db]
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin: