[package]
name = "app_core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
anyhow = "1.0"
dotenvy = "0.15"

diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"], optional = true }
odoo-api = { version = "0.2.5", features = ["blocking"],  optional = true}
serde_json = { version = "1.0.151", optional = true }

[features]
default = ["data_odoo"]

data_sqlite = ["dep:diesel"]
data_odoo = ["dep:odoo-api", "dep:serde_json"]
